AWSTemplateFormatVersion: 2010-09-09
Description: A template that deploys a defaut S3 bucket

Resources:
  SampleS3Bucket:
    Type: AWS::S3::Bucket
    Properties:     
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      
          -
